export const GAME = Object.freeze({
  width: 960,
  height: 540,
  gravity: 1120,
  flapVelocity: -350,
  maxFall: 560,
  scrollSpeed: 212,
  scrollSpeedMaxBonus: 230,
  lavaSpeedBonus: 150,
  lavaScoreMultiplier: 1.55,
  spawnEvery: 1.28,
  itemEvery: 1.1,
  maxEnergy: 100,
  damageCooldown: 0.85,
  leaderboardSize: 10,
  storageKey: "kemi-fly-leaderboard-v1",
  lavaDuration: 12,
  magnetDuration: 6.5,
  slowDuration: 4.8,
  glideDuration: 4.2,
  boostDuration: 3.6,
  levelThresholds: [0, 3, 7, 12, 18, 25],
  comboMilestone: 5,
  lowEnergyThreshold: 38,
  routePhases: [
    { distance: 0, label: "초원 항로", detail: "수정 트레일로 리듬 익히기" },
    { distance: 160, label: "초원 협곡", detail: "장애물 예고를 보고 길 선택" },
    { distance: 430, label: "사막 유적", detail: "낮은 구조물과 공중 장애물 읽기" },
    { distance: 820, label: "하늘섬 항로", detail: "회복 아이템과 실드 관리" },
    { distance: 1350, label: "마스터 항로", detail: "용암 포탈은 선택형 고난도 도전" },
  ],
  stages: [
    {
      distance: 0,
      id: "grass",
      label: "STAGE 1 초원",
      detail: "초원과 숲섬 사이를 지나갑니다",
      backgroundKey: "stageGrassBackground",
    },
    {
      distance: 430,
      id: "desert",
      label: "STAGE 2 사막",
      detail: "사막 유적 위로 더 빠르게 비행합니다",
      backgroundKey: "stageDesertBackground",
    },
    {
      distance: 820,
      id: "sky",
      label: "STAGE 3 하늘섬",
      detail: "푸른하늘 공중섬 항로에 진입합니다",
      backgroundKey: "background",
    },
  ],
});

export const ASSET_PATHS = Object.freeze({
  background: "./assets/sky-background.png",
  stageGrassBackground: "./assets/stage-grass-background.png",
  stageDesertBackground: "./assets/stage-desert-background.png",
  lavaBackground: "./assets/lava-background.png",
  backgroundPlayfield: "./assets/background-playfield.png",
  stageBurst: "./assets/stage-burst-effect.png",
  stageBadge: "./assets/stage-badge-ui.png",
  logo: "./assets/ui-logo.png",
  gameOverBanner: "./assets/ui-game-over.png",
  kemi1: "./assets/kemi-frame-1.png",
  kemi2: "./assets/kemi-frame-2.png",
  kemi3: "./assets/kemi-frame-3.png",
  kemiLv1Frame1: "./assets/kemi-lv1-frame-1.png",
  kemiLv1Frame2: "./assets/kemi-lv1-frame-2.png",
  kemiLv1Frame3: "./assets/kemi-lv1-frame-3.png",
  kemiLv2Frame1: "./assets/kemi-lv2-frame-1.png",
  kemiLv2Frame2: "./assets/kemi-lv2-frame-2.png",
  kemiLv2Frame3: "./assets/kemi-lv2-frame-3.png",
  kemiLv3Frame1: "./assets/kemi-lv3-frame-1.png",
  kemiLv3Frame2: "./assets/kemi-lv3-frame-2.png",
  kemiLv3Frame3: "./assets/kemi-lv3-frame-3.png",
  kemiLv4Frame1: "./assets/kemi-lv4-frame-1.png",
  kemiLv4Frame2: "./assets/kemi-lv4-frame-2.png",
  kemiLv4Frame3: "./assets/kemi-lv4-frame-3.png",
  kemiLv5Frame1: "./assets/kemi-lv5-frame-1.png",
  kemiLv5Frame2: "./assets/kemi-lv5-frame-2.png",
  kemiLv5Frame3: "./assets/kemi-lv5-frame-3.png",
  kemiLv6Frame1: "./assets/kemi-lv6-frame-1.png",
  kemiLv6Frame2: "./assets/kemi-lv6-frame-2.png",
  kemiLv6Frame3: "./assets/kemi-lv6-frame-3.png",
  happy: "./assets/kemi-happy.png",
  hit: "./assets/kemi-hit.png",
  crystal: "./assets/item-blue-crystal.png",
  goldCrystal: "./assets/item-gold-crystal.png",
  aiCloud: "./assets/ai-cloud.png",
  smileCloud: "./assets/item-smile-cloud.png",
  shield: "./assets/item-wing-shield.png",
  star: "./assets/item-star.png",
  feather: "./assets/item-feather.png",
  magnet: "./assets/item-magnet.png",
  hourglass: "./assets/item-hourglass.png",
  energyBolt: "./assets/item-energy-bolt.png",
  heart: "./assets/item-heart.png",
  lavaPortal: "./assets/item-lava-portal.png",
  stoneIsland: "./assets/obstacle-stone-island.png",
  stoneCluster: "./assets/obstacle-stone-cluster.png",
  boulder: "./assets/obstacle-boulder.png",
  purpleCrystal: "./assets/obstacle-purple-crystal.png",
  iceSpike: "./assets/obstacle-ice-spike.png",
  purpleStorm: "./assets/obstacle-purple-storm.png",
  thornRing: "./assets/obstacle-thorn-ring.png",
  ruinArch: "./assets/obstacle-ruin-arch.png",
  stoneCube: "./assets/obstacle-stone-cube.png",
  lavaComet: "./assets/obstacle-lava-comet.png",
  lavaBall: "./assets/obstacle-lava-ball.png",
  purplePlatform: "./assets/obstacle-purple-platform.png",
  pillarSmall: "./assets/obstacle-crystal-pillar-small.png",
  floatingRock: "./assets/obstacle-floating-rock.png",
  pillarThin: "./assets/obstacle-pillar-thin.png",
  pillarTall: "./assets/obstacle-pillar-tall.png",
  pillarRoyal: "./assets/obstacle-pillar-royal.png",
  stormHeavy: "./assets/obstacle-storm-heavy.png",
  stormBlue: "./assets/obstacle-storm-blue.png",
  spikeBall: "./assets/obstacle-spike-ball.png",
  spikeComet: "./assets/obstacle-spike-comet.png",
  spikeCometHeavy: "./assets/obstacle-spike-comet-heavy.png",
});

export const MEDIA_PATHS = Object.freeze({
  bgm: "./assets/bgm-running-past-clouds.mp3",
  sfx: Object.freeze({
    flap: "./assets/sfx/01-flap-wing-pop.wav",
    collect: "./assets/sfx/02-crystal-collect-blue.wav",
    gold: "./assets/sfx/03-gold-crystal-bonus.wav",
    heal: "./assets/sfx/04-ai-cloud-heal.wav",
    shield: "./assets/sfx/05-shield-on.wav",
    magnet: "./assets/sfx/05-shield-on.wav",
    slow: "./assets/sfx/04-ai-cloud-heal.wav",
    boost: "./assets/sfx/09-fever-combo.wav",
    lava: "./assets/sfx/07-damage-soft-hit.wav",
    near: "./assets/sfx/06-near-miss-whoosh.wav",
    damage: "./assets/sfx/07-damage-soft-hit.wav",
    levelup: "./assets/sfx/08-level-up-bright.wav",
    fever: "./assets/sfx/09-fever-combo.wav",
    gameover: "./assets/sfx/10-game-over-gentle.wav",
    start: "./assets/sfx/11-button-start.wav",
    button: "./assets/sfx/11-button-start.wav",
  }),
});

export const SUPPORT_URL = "https://safe.menlosecurity.com/mpa/1/https://demian2.ai-playground.ktcloud.com/#apply";

export const TITLES = Object.freeze([
  { score: 20000, label: "케미 마스터" },
  { score: 10000, label: "하늘섬의 영웅" },
  { score: 5000, label: "수정 수집가" },
  { score: 3000, label: "구름 탐험가" },
  { score: 1000, label: "첫 날갯짓" },
  { score: 0, label: "새싹 비행가" },
]);
