export const GAME = Object.freeze({
  width: 960,
  height: 540,
  gravity: 1300,
  flapVelocity: -430,
  maxFall: 620,
  scrollSpeed: 215,
  scrollSpeedMaxBonus: 210,
  spawnEvery: 1.35,
  itemEvery: 1.1,
  maxEnergy: 100,
  damageCooldown: 0.85,
  leaderboardSize: 10,
  storageKey: "kemi-fly-leaderboard-v1",
  lavaDistance: 420,
  levelThresholds: [0, 3, 7, 12, 18, 25],
});

export const ASSET_PATHS = Object.freeze({
  background: "./assets/sky-background.png",
  lavaBackground: "./assets/lava-background.png",
  backgroundPlayfield: "./assets/background-playfield.png",
  logo: "./assets/ui-logo.png",
  gameOverBanner: "./assets/ui-game-over.png",
  kemi1: "./assets/kemi-frame-1.png",
  kemi2: "./assets/kemi-frame-2.png",
  kemi3: "./assets/kemi-frame-3.png",
  kemiLv1Frame1: "./assets/kemi-lv1-frame-1.png",
  kemiLv1Frame2: "./assets/kemi-lv1-frame-2.png",
  kemiLv1Frame3: "./assets/kemi-lv1-frame-3.png",
  kemiLv2Frame1: "./assets/kemi-lv2-frame-1.png",
  kemiLv2Frame2: "./assets/kemi-lv2-frame-2.png",
  kemiLv2Frame3: "./assets/kemi-lv2-frame-3.png",
  kemiLv3Frame1: "./assets/kemi-lv3-frame-1.png",
  kemiLv3Frame2: "./assets/kemi-lv3-frame-2.png",
  kemiLv3Frame3: "./assets/kemi-lv3-frame-3.png",
  kemiLv4Frame1: "./assets/kemi-lv4-frame-1.png",
  kemiLv4Frame2: "./assets/kemi-lv4-frame-2.png",
  kemiLv4Frame3: "./assets/kemi-lv4-frame-3.png",
  kemiLv5Frame1: "./assets/kemi-lv5-frame-1.png",
  kemiLv5Frame2: "./assets/kemi-lv5-frame-2.png",
  kemiLv5Frame3: "./assets/kemi-lv5-frame-3.png",
  kemiLv6Frame1: "./assets/kemi-lv6-frame-1.png",
  kemiLv6Frame2: "./assets/kemi-lv6-frame-2.png",
  kemiLv6Frame3: "./assets/kemi-lv6-frame-3.png",
  happy: "./assets/kemi-happy.png",
  hit: "./assets/kemi-hit.png",
  crystal: "./assets/item-blue-crystal.png",
  goldCrystal: "./assets/item-gold-crystal.png",
  aiCloud: "./assets/ai-cloud.png",
  smileCloud: "./assets/item-smile-cloud.png",
  shield: "./assets/item-wing-shield.png",
  star: "./assets/item-star.png",
  feather: "./assets/item-feather.png",
  magnet: "./assets/item-magnet.png",
  hourglass: "./assets/item-hourglass.png",
  energyBolt: "./assets/item-energy-bolt.png",
  heart: "./assets/item-heart.png",
  stoneIsland: "./assets/obstacle-stone-island.png",
  stoneCluster: "./assets/obstacle-stone-cluster.png",
  boulder: "./assets/obstacle-boulder.png",
  purpleCrystal: "./assets/obstacle-purple-crystal.png",
  iceSpike: "./assets/obstacle-ice-spike.png",
  purpleStorm: "./assets/obstacle-purple-storm.png",
  thornRing: "./assets/obstacle-thorn-ring.png",
  ruinArch: "./assets/obstacle-ruin-arch.png",
  stoneCube: "./assets/obstacle-stone-cube.png",
  lavaComet: "./assets/obstacle-lava-comet.png",
  lavaBall: "./assets/obstacle-lava-ball.png",
  purplePlatform: "./assets/obstacle-purple-platform.png",
  pillarSmall: "./assets/obstacle-crystal-pillar-small.png",
  floatingRock: "./assets/obstacle-floating-rock.png",
  pillarThin: "./assets/obstacle-pillar-thin.png",
  pillarTall: "./assets/obstacle-pillar-tall.png",
  pillarRoyal: "./assets/obstacle-pillar-royal.png",
  stormHeavy: "./assets/obstacle-storm-heavy.png",
  stormBlue: "./assets/obstacle-storm-blue.png",
  spikeBall: "./assets/obstacle-spike-ball.png",
  spikeComet: "./assets/obstacle-spike-comet.png",
  spikeCometHeavy: "./assets/obstacle-spike-comet-heavy.png",
});

export const MEDIA_PATHS = Object.freeze({
  bgm: "./assets/bgm-running-past-clouds.mp3",
  intro: "./assets/intro-kemi-hatch.mp4",
});

export const TITLES = Object.freeze([
  { score: 20000, label: "케미 마스터" },
  { score: 10000, label: "하늘섬의 영웅" },
  { score: 5000, label: "수정 수집가" },
  { score: 3000, label: "구름 탐험가" },
  { score: 1000, label: "첫 날갯짓" },
  { score: 0, label: "새싹 비행가" },
]);
